### ISSUE TITLE
Feature: improving the menu configuration system

### ISSUE THREAD

**Issue by Zarkness** [Auxilor/EcoCrates#1]
**Is your feature request related to a problem? Please describe.**
I saw that you have a system of patterns to manage the menus and my idea was to make the items you can put a number, letter or symbol, as in the picture below, since it does not look very good a system of patterns and you place the items by row and column.

if something is not well understood, let me know and I will try to explain it better.

**Additional context**
![imagen_2022-03-17_163809](https://user-images.githubusercontent.com/48263644/158836628-6f954c1b-a887-4571-9cf4-0c5f132129bc.png)

the image is taken from a menu plugin that I use

**Comment by WillFP** [comment]
That's already how it works with the mask system? You just add many items as you want and then reference them with 1,2,3,4,5, etc
