### ISSUE TITLE
Commands or GUI to add items to crates

### ISSUE THREAD

**Issue by ToonamiSenpai** [Auxilor/EcoCrates#10]
**Is your feature request related to a problem? Please describe.**
Not being able to put Sulkers boxes filled with items in a crate.

**Describe the solution you'd like**
Maybe a command or GUI That you can hold the items you want to be added or drag and drop the items you want added to a creat

**Describe alternatives you've considered**
It's on most other Crates plugins and just makes the initial setup easier, and then for more of the custom stuff you can edit the file

**Comment by WillFP** [comment]
In-game GUIs are a pain in the ass, I won't be adding this - a web panel is potentially possible in the future
