### ISSUE TITLE
Placeholders arent working in holograms

### ISSUE THREAD

**Issue by 1ntent1on** [Auxilor/EcoCrates#11]
**Describe the bug**
Hello, i tried putting placeholders into crates hologram (using Decent Holograms), but they dont work. Also i was getting that error https://pastebin.com/2VbqhupC

**To Reproduce**
1. Put any placeholder into crates holograms for example %ecocrates_demo_keys% for the demo crate.
 
**Expected behavior**
There should be proper value of the placeholder, instead theres nothing.

**Screenshots**

**Server Information (please complete the following information):**
- Version: (output of `/ver` command) Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`) eco version 6.31.0, EcoCrates version 1.3.3, DecentHolograms version 2.3.1

**Additional context**
I have also tried putting placeholder for random number into win command and it also didnt work. I had command like that
"lp user %player% parent addtemp rank %cmi_random_1_5%d accumulate"

**Comment by WillFP** [comment]
limitation of the hologram plugind
