### ISSUE TITLE
Item order based on order listed in crates.yml

### ISSUE THREAD

**Issue by good3n** [Auxilor/EcoCrates#15]
As of right now the rewards are defined in the `rewards.yml` file. Which at first I liked (and I guess I still do) because it would allow you to use the same item in multiple crates without defining it multiple times. However, due to the fact that the row and column is also defined at the reward level, you need to make sure if you're using the same reward in multiple crates, that the item is in the exact same spot in all of them.

I propose giving us the option to not have to define the row and column and instead allow us to determine the order based on the order they're listed in the rewards defined in the `crates.yml` file.

Crazy Crates allows us to do this currently.

**Comment by WillFP** [comment]
done as of a few versions ago
