### ISSUE TITLE
Rework weight system

### ISSUE THREAD

**Issue by Lariesse** [Auxilor/EcoCrates#17]
I'm always frustrated when I need to set a change of winning a reward. The weight system changes massively if you add or remove items, and if you change rewards in a crate, you have to change the weight of all other existing rewards.

I suggest that the chances of winning a reward shouldn't be through the total sum of rewards in a crate, they should be separate values for each reward.

**Comment by WillFP** [comment]
You don't have to change the weight of any existing rewards? If you add items, the weight is divided evenly between the items - this is how it works in every crates plugin
