### ISSUE TITLE
Random-reward

### ISSUE THREAD

**Issue by LeAnhTuan0810** [Auxilor/EcoCrates#3]
**Describe the bug**
When I set the crate and then go away from the crate and come back, it crashes

**Screenshots**
https://file.coffee/u/alzZM1EC8OjTjv.png

**Server Information (please complete the following information):**
- Version: 1.18.2
- Version of plugin and eco 6.29.1 & 1.0.1

**Comment by WillFP** [comment]
Fix coming in next version

**Comment by LeAnhTuan0810** [comment]
> Fix coming in next version

hm 1.0.2 still error
