### ISSUE TITLE
Crate reload apocalypse

### ISSUE THREAD

**Issue by good3n** [Auxilor/EcoCrates#6]
After installing the plugin, I set a crate to `demo` via `/ecocrates set demo` while looking at a crate. After that, using `/ecocrates reload` I get the following after a few reloads:

![error1](https://i.gyazo.com/de35c033ea378d7cf0e830ca4dd359d8.png)

As you can see it gets worse with every reload until it just crashes the server. I then open my `placedcrates.yml` to see why my crate is gone after the server starts from the crash and find this:

![error2](https://i.gyazo.com/f887df3065ebb377f6e95c612b400ae0.png)

5000+ lines of `# This file is for internal storage only.` followed by my crate location.

Here is a pastebin of the crash: https://pastebin.com/E6DmJ5rr

**Comment by WillFP** [comment]
Fixed in latest eco
