### ISSUE TITLE
Forceopen command working on console

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoCrates#9]
**Is your feature request related to a problem? Please describe.**
Hey after switching from CrateReloaded to EcoCrates I have 1 major thing that is quite annoying. EcoCrates has a command to forceopen a crate without having the key. I have a huge system when doing X things I will force open a "crate" (not an actual crate, I just use the system behind it). The issue with ecocrates is that the command is only executable in game and there is no player argument to the command

**Describe the solution you'd like**
Adding support to console and adding the player argument to this command: /ecocrates forceopen CRATE -> /ecocrates forceopen Crate %player%

**Describe alternatives you've considered**
CrateReloaded

**Additional context**
Eco <3

**Comment by WillFP** [comment]
been done a while ago now
